### ISSUE TITLE
No response after being opened, MacOS 10.15.3

### ISSUE THREAD

**Issue by INPUTrrr0** [bhaller/Jiggler#13]
Hello, hopefully this is the right place? 
After I downloaded it from CNET and opened the dmg, I dragged the application into the application folder and ejected the disk. I tried to open it from there. It prompted me to change the accessibility to allow cursor access. After I did that, I opened Jiggler again from the applications. However there was no response. The dock area also do not show the Jiggler icon. I tried again but this time I clicked on the dmg file and clicked on the application from the disk directly. Again there was no response. However this time when I try to eject the disk, it prompts me that the software is still in use so the disk cannot be ejected. So seems like it should be running but there is just no sign at all, no window displayed etc. 
Please kindly enlighten me as to how to solve this issue. 

Thanks!

------
Edit: Sorry. Seems like there is just no window? It will automatically turn on when the mouse is not moving for a certain time? I  have another question. Since it also does not show the icon in the dock area, what happens if I want to close it and see the screensaver? Thanks again! Please tell me if there is any misunderstanding.

**Comment by bhaller** [comment]
Please read the README file that comes with Jiggler in the dmg.  Jiggler does not appear in your dock; it appears as an icon in your menu bar.  It can be controlled from there – including quitting it so that you can eject the dmg.

**Comment by INPUTrrr0** [comment]
Oh I see! I am so sorry for the trouble. Thank you for your response and this lovely software!
