### ISSUE TITLE
New feature: run native on Apple architecture for M1

### ISSUE THREAD

**Issue by aboshuizen** [bhaller/Jiggler#16]
Now the M1 chip is being used in the new Macs, it would be great to support
 this.

**Comment by bhaller** [comment]
Indeed.  Will have to wait until I have an M1-based machine to test on, though.

**Comment by unready** [comment]
> Now the M1 chip is being used in the new Macs, it would be great to support
> this.

You can just clone this repo (source code), open it in Xcode, build it and use the output (Jiggler). It says Architecture "Apple" and not "Intel" (when looking in Activity Monitor), when I run it after building the source code myself.  Did a quick test on my Mac Mini M1 making no changes to the code.

**Comment by aboshuizen** [comment]
Yes, I didn't think of that. Works for me: thanks. Maybe release a version so people not into coding can use this?

**Comment by bhaller** [comment]
It will happen.  Busy over here.  :->

**Comment by bhaller** [comment]
OK, version 1.9 has just been released, which is Universal and fixes a bug or two.  Download it from sticksoftware.com.  Closing this issue now.

**Comment by andschwa** [comment]
Just downloaded and ran on an M1, working great and Activity Monitor verified that it's running natively.

**Comment by bhaller** [comment]
Thanks for testing!
