### ISSUE TITLE
Is there a way to enable Jiggler but allowing the screen to dim/turn off?

### ISSUE THREAD

**Issue by sxflynn** [bhaller/Jiggler#17]
I want to enable Jiggler so that my VMWare Horizon Client remote connection doesn't automatically switch off after about 15 minutes of idle. Is there a way I can activate Jiggler but then somehow have the Mac screen turn off? I'm using a Macbook Pro in clamshell mode with an external mini Displayport monitor.

**Comment by bhaller** [comment]
That isn't supported, sorry – I don't know how I would even do it.  I'm not sure you can allow the screen to turn off while simultaneously having the machine think that it is not idle.
