### ISSUE TITLE
1.9 doesn't work on Mojave (10.14.6)

### ISSUE THREAD

**Issue by pareis** [bhaller/Jiggler#22]
Recently upgraded from 1.8 to 1.9 on 10.14.6 and when starting it up it shows the error message:

"You can’t use this version of the application “Jiggler.app” with this version of macOS."
"You have macOS 10.14.6. The application requires macOS 10.15 or later."

![Screen Shot 2021-07-12 at 13 42 53](https://user-images.githubusercontent.com/926591/125218431-14580d80-e317-11eb-802d-652138236956.png)

Is that on purpose or by accident?

**Comment by bhaller** [comment]
It is on purpose.  If you want to run Jiggler on an older version of macOS, download the appropriate version from http://www.sticksoftware.com/archive.html.
