### ISSUE TITLE
Doesn't work on MacOS Sequoia Version 15.0.1

### ISSUE THREAD

**Issue by activea** [bhaller/Jiggler#32]
Jiggler window doesn't open on MacOS Sequoia Version 15.0.1 and although it seems to begin running.. it doesn't work fine!!

**Comment by bhaller** [comment]
Yes, Apple seems to have broken Jiggler once again.  I don't have time to fix it; in the face of Apple's relentless determination to break all of my software, I'm afraid I am being forced to give up.  Jiggler is open-source here on GitHub, and I'd be happy to accept a pull request from someone with a fix.  I'm not even on Sequoia yet, and can't upgrade to it for quite some time yet, so I have no idea what the problem might be.

**Comment by dansmachina** [comment]
I'm on Sequoia 15.0.1 and it works perfectly for me. 

<img width="1512" alt="Screenshot 2024-10-13 at 09 47 12" src="https://github.com/user-attachments/assets/8d520484-b552-4698-b831-c68d5ae4bb20">

**Comment by bhaller** [comment]
> I'm on Sequoia 15.0.1 and it works perfectly for me.

Aha, interesting!  Hmm.  Well, @activea, are you definitely running the latest version?  And you do know where to find Jiggler's preferences and such, through its menu bar icon?

**Comment by activea** [comment]
I have uninstalled and installed the latest version and it works now!! Thank you!!

**Comment by bhaller** [comment]
OK, sounds like it works on 15.0.1 for everyone, which is great to know!  Closing this issue.
