### ISSUE TITLE
New Feature: Customisable amount of cursor movement

### ISSUE THREAD

**Issue by james-ovens** [bhaller/Jiggler#5]
I've used Jiggler for a long time now and its great. At the new place I am working at the VPN disconnects when my mac is inactive for a very short period of time (even just a few minutes). I am trying to use Jiggler to prevent this however it seems that small amounts of mouse jiggling don't seem to keep the connection alive, (including when I jiggle the mouse manually), however large amounts of jiggling seems to do the trick.

I'm not sure how difficult it would be but having a slider in the preferences similar to the one used for setting the interval between jiggles would be great for a 'jiggle amount' setting which would allow users to increase or decrease the amount the mouse cursor is moved (and potentially another for how long the mouse is moved for).

Does this sound possible?

**Comment by bhaller** [comment]
It's certainly possible; the main difficulty is making the user interface for it, really, not implementing the underlying feature.  If you're comfortable developing in Xcode, I'd suggest that you just make your own private copy of Jiggler with a larger jiggle distance.  I might add this feature eventually, but I'm really not doing much active development on it these days, so it might take a long time (i.e., months to years), or more likely it won't happen at all.

**Comment by bhaller** [comment]
This is fixed in Jiggler 1.8, just released.
