### ISSUE TITLE
New feature: Auto click mouse feature option 

### ISSUE THREAD

**Issue by srids** [bhaller/Jiggler#7]

**Comment by bhaller** [comment]
Dangerous, since the mouse could be over anything, especially after it jiggles a couple of times, no?  What's the motivation?

**Comment by srids** [comment]
dont think its dangerous if its done right. programs like 
http://www.murgaa.com/auto-clicker-mac/ already do albeit without system idle check which Jiggler does nicely.
i meant to add it as either option between mouse jiggle OR mouse click. not both. with both, it could be dangerous.
motivation is that some applications (chat apps for e.g.) check on not if mouse jiggled but rather if mouse clicked to report application idle status.

**Comment by bhaller** [comment]
This is fixed in Jiggler 1.8, just released.
